/// Table ccTLD -> pays. Volontairement limitée aux domaines qui
/// permettent RAISONNABLEMENT d'identifier un pays. Les domaines
/// génériques/internationaux (.com, .org, gmail.com, etc.) ne sont
/// JAMAIS dans cette table : ils restent "indéterminés" par principe.
const Map<String, String> ccTldToCountry = {
  'fr': 'France',
  'de': 'Allemagne',
  'it': 'Italie',
  'es': 'Espagne',
  'se': 'Suède',
  'be': 'Belgique',
  'ch': 'Suisse',
  'nl': 'Pays-Bas',
  'pt': 'Portugal',
  'at': 'Autriche',
  'pl': 'Pologne',
  'gr': 'Grèce',
  'dk': 'Danemark',
  'fi': 'Finlande',
  'no': 'Norvège',
  'ie': 'Irlande',
  'lu': 'Luxembourg',
  'ro': 'Roumanie',
  'hu': 'Hongrie',
  'cz': 'République tchèque',
  'sk': 'Slovaquie',
  'bg': 'Bulgarie',
  'hr': 'Croatie',
  'si': 'Slovénie',
  'ee': 'Estonie',
  'lv': 'Lettonie',
  'lt': 'Lituanie',
  'mt': 'Malte',
  'cy': 'Chypre',
  'uk': 'Royaume-Uni',
  'gb': 'Royaume-Uni',
  'ru': 'Russie',
  'ua': 'Ukraine',
  'tr': 'Turquie',
  'ma': 'Maroc',
  'dz': 'Algérie',
  'tn': 'Tunisie',
  'sn': 'Sénégal',
  'ci': 'Côte d\'Ivoire',
  'bj': 'Bénin',
  'tg': 'Togo',
  'ng': 'Nigeria',
  'gh': 'Ghana',
  'cm': 'Cameroun',
  'cd': 'RD Congo',
  'cg': 'Congo',
  'za': 'Afrique du Sud',
  'eg': 'Égypte',
  'ke': 'Kenya',
  'us': 'États-Unis',
  'ca': 'Canada',
  'mx': 'Mexique',
  'br': 'Brésil',
  'ar': 'Argentine',
  'cl': 'Chili',
  'co': 'Colombie',
  'pe': 'Pérou',
  'cn': 'Chine',
  'jp': 'Japon',
  'kr': 'Corée du Sud',
  'in': 'Inde',
  'id': 'Indonésie',
  'th': 'Thaïlande',
  'vn': 'Vietnam',
  'ph': 'Philippines',
  'my': 'Malaisie',
  'sg': 'Singapour',
  'au': 'Australie',
  'nz': 'Nouvelle-Zélande',
  'sa': 'Arabie saoudite',
  'ae': 'Émirats arabes unis',
  'il': 'Israël',
  'qa': 'Qatar',
};

/// Domaines volontairement JAMAIS classés par pays (trop génériques,
/// utilisés dans le monde entier), quel que soit leur ccTLD apparent.
const Set<String> internationalDomains = {
  'gmail.com',
  'googlemail.com',
  'outlook.com',
  'hotmail.com',
  'hotmail.fr',
  'hotmail.co.uk',
  'live.com',
  'yahoo.com',
  'yahoo.fr',
  'icloud.com',
  'me.com',
  'aol.com',
  'protonmail.com',
  'proton.me',
  'zoho.com',
  'gmx.com',
  'gmx.net',
  'mail.com',
};
